# import library & define functions

In [1]:
import pandas as pd
import numpy as np
import sudoku
import importlib
importlib.reload(sudoku)

/Users/ikk/.pyenv/versions/3.6.8/envs/python3/lib/python3.6/site-packages/pandas/compat/__init__.py:117: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


<module 'sudoku' from '/Users/ikk/python/code/sudoku/sudoku.py'>

# import data

In [2]:
result = np.loadtxt('input_data/test_87.csv', delimiter=',', dtype='int64')
sudoku = sudoku.Sudoku(result)

imported data: null size: 63


unresolved size: 63


# calc

In [3]:
sudoku.calc()

before 1


unresolved size: 62
cand_indexes:


0  1  2  3  4  5  6  7  8  9  10  11  12  13  14
0  0  0  0  1  1  3  3  3  4  4   6   6   6   8   8
1  1  3  4  2  3  1  2  7  1  7   3   4   8   4   8

dup_res 0:


array([[0, 2, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 6, 2, 9, 0, 0, 1, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 1


array([[0, 6, 4, 2, 0, 0, 7, 0, 0],
       [0, 3, 2, 0, 9, 0, 0, 6, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 2, 0, 0, 4, 7],
       [2, 7, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 6]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 2


array([[0, 6, 4, 0, 2, 0, 7, 0, 0],
       [0, 3, 2, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 2, 0, 0, 0, 4, 7],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 2]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 3


array([[0, 6, 4, 2, 0, 0, 7, 0, 0],
       [0, 3, 2, 0, 9, 0, 0, 6, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 1, 0, 0, 0, 0, 4, 7],
       [2, 7, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 7, 0, 8, 6]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 4


array([[0, 2, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 6, 2, 9, 0, 0, 1, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 5


array([[0, 6, 4, 2, 0, 0, 7, 0, 0],
       [0, 3, 2, 7, 9, 0, 0, 6, 0],
       [8, 0, 7, 4, 0, 6, 2, 0, 5],
       [0, 2, 6, 0, 0, 0, 0, 0, 0],
       [7, 0, 8, 3, 6, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 1, 0, 0, 0, 0, 4, 7],
       [2, 7, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 7, 0, 8, 6]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 6


array([[0, 2, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 6, 2, 9, 0, 0, 1, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 7


array([[0, 6, 4, 2, 0, 0, 7, 0, 0],
       [0, 3, 2, 0, 9, 0, 0, 6, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 6, 0, 0, 0, 0, 2, 0],
       [0, 2, 8, 3, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 1, 0, 0, 0, 0, 4, 7],
       [2, 7, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 7, 0, 8, 6]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 8


array([[0, 6, 4, 2, 0, 0, 7, 0, 0],
       [0, 3, 2, 0, 9, 0, 0, 6, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 6, 0, 0, 0, 0, 2, 0],
       [0, 2, 8, 3, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 1, 0, 0, 0, 0, 4, 7],
       [2, 7, 0, 6, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 7, 0, 8, 6]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 9


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

result 10


array([[0, 6, 4, 0, 2, 0, 7, 0, 0],
       [0, 3, 2, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 2, 0, 0, 0, 4, 7],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 2]])

dup_res > 0:


array([[0, 0, 4, 0, 0, 0, 7, 0, 0],
       [0, 3, 0, 0, 9, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 6, 2, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 6, 0, 0],
       [6, 8, 0, 0, 0, 0, 0, 4, 0],
       [2, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 8, 0]])

complete!


True

# display result

In [4]:
sudoku.display_result()

unresolved size: 0


# display remaining candidate (if failed)

In [5]:
sudoku.display_remaining_candidate()